name: test
on: [push]
jobs:
  job-thing:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: dump-job-status
        env:
          JOB_STATUS: ${{ job.status }}
        run: echo "$JOB_STATUS"
